service: test-api

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    EMPLOYEES_TABLE_NAME: ${self:custom.EmployeesTable.name}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - ${file(iam/EmployeesTableIAM.yml):EmployeesTableIAM}

resources:
  Resources:
    EmployeesTable: ${file(resources/EmployeesTable.yml):EmployeesTable}

functions:
  random:
    handler: src/handlers/random.handler
    events:
      - http:
          method: GET
          path: /random
      - http:
          method: GET
          path: /random/{name}
      - http:
          method: GET
          path: /random/{name}/{method}
  addEmployee:
    handler: src/handlers/addEmployee.handler
    events:
      - http:
          method: POST
          path: /employee
  getEmployees:
    handler: src/handlers/getEmployees.handler
    events:
      - http:
          method: GET
          path: /employees
  getEmployee:
    handler: src/handlers/getEmployee.handler
    events:
      - http:
          method: GET
          path: /employee/{id}

custom:
  EmployeesTable:
    name: !Ref EmployeesTable
    arn: !GetAtt EmployeesTable.Arn
  bundle:
    linting: false
