service:
  name: test-api

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221

functions:
  random:
    handler: src/handlers/random.handler
    events:
      - http:
          method: GET
          path: /random
      - http:
          method: GET
          path: /random/{name}
      - http:
          method: GET
          path: /random/{name}/{method}
