WSConnectionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: WSConnectionsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
    KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
